# Generated by Django 5.0.6 on 2025-09-21 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ediserviceline',
            name='diagnosis_pointers',
        ),
        migrations.CreateModel(
            name='EDIServiceLineDiagnosisPointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointer_order', models.PositiveSmallIntegerField(choices=[(1, 'Pointer 1'), (2, 'Pointer 2'), (3, 'Pointer 3'), (4, 'Pointer 4')], help_text='Order of this diagnosis pointer in SV107 (max 4).')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointer_links', to='superbill.ediclaimdiagnosis')),
                ('service_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_pointer_links', to='superbill.ediserviceline')),
            ],
            options={
                'db_table': 'superbill_edi_service_line_pointer',
                'ordering': ['pointer_order'],
                'unique_together': {('service_line', 'pointer_order')},
            },
        ),
    ]
