# Generated by Django 5.2.9 on 2026-01-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbill', '0002_remove_ediserviceline_diagnosis_pointers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edipayerendpoint',
            options={'verbose_name': 'EDI Payer Endpoint', 'verbose_name_plural': 'EDI Payer Endpoints'},
        ),
        migrations.AlterModelOptions(
            name='edisegment',
            options={'verbose_name': 'EDI Segment', 'verbose_name_plural': 'EDI Segments'},
        ),
        migrations.AddField(
            model_name='ediloop',
            name='max_repeat',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='edipayerrule',
            name='target_type',
            field=models.CharField(choices=[('ELEMENT', 'Element'), ('LOOP', 'Loop')], default='ELEMENT', max_length=10),
        ),
    ]
