# Generated by Django 5.2.9 on 2026-01-08 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbill', '0003_alter_edipayerendpoint_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edisegment',
            name='loop',
            field=models.ForeignKey(help_text='The loop this segment belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='superbill.ediloop'),
        ),
    ]
