# Generated by Django 5.2.9 on 2026-01-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbill', '0004_alter_edisegment_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='edielement',
            name='x12_id',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
