# Generated by Django 5.2.9 on 2026-01-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbill', '0005_edielement_x12_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='edielement',
            name='required',
            field=models.BooleanField(default=False, help_text='Indicates if this element is required in the segment.'),
        ),
        migrations.AlterField(
            model_name='edielement',
            name='x12_id',
            field=models.CharField(help_text="X12 element identifier (e.g., 'NM1', 'DTM').", max_length=10),
        ),
    ]
