# Generated by Django 5.2.9 on 2026-01-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbill', '0006_edielement_required_alter_edielement_x12_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edielement',
            name='length',
            field=models.PositiveIntegerField(blank=True, default=50, help_text='Maximum length allowed for this element.', null=True),
        ),
    ]
