# Generated by Django 5.2.10 on 2026-01-08 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbill', '0007_alter_edielement_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='edipayerrule',
            name='loop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superbill.ediloop'),
        ),
    ]
