# Generated by Django 5.2.10 on 2026-01-08 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbill', '0008_edipayerrule_loop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edipayerrule',
            name='element',
            field=models.ForeignKey(blank=True, help_text='The EDI element this rule applies to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='superbill.edielement'),
        ),
    ]
