# Generated by Django 5.2.10 on 2026-01-09 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbill', '0009_alter_edipayerrule_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edipayerrule',
            name='loop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='superbill.ediloop'),
        ),
    ]
