# Generated by Django 5.2.10 on 2026-01-11 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbill', '0010_alter_edipayerrule_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='edielement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_elements', to='superbill.edielement'),
        ),
    ]
