# Generated by Django 5.2.10 on 2026-01-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbill', '0011_edielement_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='edisegment',
            name='max_repeat',
            field=models.IntegerField(default=1),
        ),
    ]
